[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tgraph-bot"
version = "1.0.0"
description = "A Discord bot for automatically generating and posting Tautulli graphs"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "engels74", email = "141435164+engels74@users.noreply.github.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications :: Chat",
    "Topic :: Multimedia :: Graphics :: Presentation",
]
requires-python = ">=3.13"
dependencies = [
    "discord.py>=2.3.0",
    "pydantic>=2.5.0",
    "matplotlib>=3.8.0",
    "seaborn>=0.13.0",
    "httpx>=0.25.0",
    "pyyaml>=6.0.0",
    "watchdog>=6.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "basedpyright>=1.8.0",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/engels74/tgraph-bot-source"
Repository = "https://github.com/engels74/tgraph-bot-source"
Issues = "https://github.com/engels74/tgraph-bot-source/issues"

[project.scripts]
tgraph-bot = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["bot", "config", "graphs", "utils"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=bot",
    "--cov=config",
    "--cov=graphs",
    "--cov=utils",
    "--cov-report=term-missing",
    "--cov-report=html",
]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["bot", "config", "graphs", "utils"]
omit = ["tests/*", "*/test_*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[dependency-groups]
dev = [
    "polib>=1.2.0",
]
