[project]
name = "tgraph-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "engels74", email = "141435164+engels74@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tgraph-bot = "tgraph_bot:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.36.2",
    "ruff>=0.14.10",
]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "N", "UP", "C90"]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.format]
docstring-code-format = true

[tool.basedpyright]
pythonVersion = "3.14"
typeCheckingMode = "recommended"
failOnWarnings = true
pythonPlatform = "All"
exclude = ["htmlcov", ".venv"]