---
extends: default

rules:
  line-length:
    max: 250
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  document-start:
    present: true
